pi_server/urls.py
from django.contrib import admin
from django.urls import path, include
from pi_home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('stream/', include('pi_stream.urls')),
    path('visitors/', include('pi_visitors.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

pi_stream/urls.py
from django.urls import path
from . import views


app_name='pi_stream'

urlpatterns = [
    path('', views.stream, name='stream'),
    path('video_feed', views.video_feed, name='video_feed')
]

pi_visitors/urls.py
from django.urls import path

from . import views

app_name='pi_visitors'

urlpatterns = [
    path('', views.visitors,name='visitors'),
    path('chooseDate', views.choose_date, name='chooseDate')
]

pi_home/models.py
from django.db import models

# Create your models here.

pi_visitors/models.py
from django.db import models

class VisitorDetection(models.Model):
    '''Contains image of detected visitor and timestamp'''
    image = models.ImageField(upload_to='pi_visitors/images/')
    detection_time = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'visitor_detection'
    
    

pi_home/views.py
from django.shortcuts import render

def home(request):
    return(render(
        request,
        'pi_home/home.html'
    ))

pi_stream/views.py
from django.shortcuts import render
from django.http import StreamingHttpResponse
from django.conf import settings
from .opencv_detection_utils.FaceDetector import FaceDetector
from .camera_service.camera_pi import Camera
from .Alarm import Alarm
from .streaming_service import stream_detections

proto_path = str(settings.FACE_PATH / 'deploy.prototxt')
model_path = str(settings.FACE_PATH / 'res10_300x300_ssd_iter_140000.caffemodel')
alarm = Alarm(
    frames_with_no_detections_threshold=30, 
    melody='ring.wav'
)

def stream(request):
    return(render(
        request,
        'pi_stream/stream.html'
    ))
    
def video_feed(response):
    detector = FaceDetector(proto_path, model_path, confidence=.4)
    return(StreamingHttpResponse(
        stream_detections(Camera(), detector, alarm), 
        content_type='multipart/x-mixed-replace; boundary=frame'
    ))

pi_visitors/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import VisitorDetection
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile

def visitors(request):
    if 'date' not in request.GET:
        visitors = VisitorDetection.objects.filter(detection_time__date=timezone.localdate())
    else:
        date = request.GET.get('date')
        visitors = VisitorDetection.objects.filter(detection_time__date=date)
    return(render(
        request,
        'pi_visitors/visitors.html',
        {'visitors': visitors}
    ))
    
def choose_date(request):
    return(render(
        request,
        'pi_visitors/choose_date.html'
    ))

# image = Image.open('sunset-picture.jpg')
    # image_io = BytesIO()
    # image.save(image_io, 'jpeg')
    # VisitorDetection.objects.create(image=ContentFile(image_io.getvalue(), name='test2.jpg'))

pi_home/templates/pi_home/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Домашний сервер</h1>
    <p>Добро пожаловать на домашний сервер. Здесь вы можете понаблюдать за тем, что происходит на улице, а также историю посещений.</p>
{% endblock %}

pi_stream/templates/pi_stream/stream.html
{% extends 'base.html' %}
{% block content %}
    <h1>Видео с камеры</h1>
    <img src="{% url 'pi_stream:video_feed' %}" class="cameraImage">
{% endblock %}

pi_visitors/templates/pi_visitors/choose_date.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'pi_visitors:visitors' %}" method="GET" class="form">
        <div class="form-group mb-medium">
            <label for="date">Дата посещения:</label>
            <input type="date" name="date" id="date">
        </div>
        <button type="submit" class="button">Посмотреть</button>
    </form>
{% endblock %} 

pi_visitors/templates/pi_visitors/visitors.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Зафиксированные Посетители</h1>
    {% for visitor in visitors %}
        <div class="visitor-card">
            <img src="{{ visitor.image.url }}" alt="" class="cameraImage--visitor cameraImage">
            <div class="visit-date mt-small">
                <p class="visit-date__memo">
                    Дата посещения:
                </p>
                <p class="visit-date__date">
                    {{ visitor.detection_time|date:'d F Y H:i' }}
                </p>
            </div>
            
        </div>
    {% endfor %}   
{% endblock %} 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="nav">
        <ul class="nav__list">
            <li class="nav__item">
                <a href="{% url 'home' %}" class="nav__link">На Главную</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'pi_stream:stream' %}" class="nav__link">Посмотреть что происходит на улице</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'pi_visitors:visitors' %}" class="nav__link">Посмотреть историю посещений</a>
                <ul class="dropdown">
                    <li class="dropdown__item">
                        <a href="{% url 'pi_visitors:visitors'%}">Сегодняшние посетители</a>
                    </li>
                    <li class="dropdown__item">
                        <a href="{% url 'pi_visitors:chooseDate'%}">Посетители в произвольный день</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>